openapi: 3.0.1
info:
  title: Document Management Service API
  description: All Management Service functionalities
  version: v0.0.1
servers:
  - url: /
    description: Default Server URL
tags:
  - name: Document Management
    description: Endpoints for document management.
paths:
  /document-management/documents/uploads:
    post:
      tags:
        - Document Management
      operationId: initiateUpload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PresignedUrlRequest'
      responses:
        '201':
          description: Presigned URL created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadUrlResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /document-management/documents:
    post:
      tags:
        - Document Management
      operationId: confirmUpload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmUploadRequest'
      responses:
        '201':
          description: Document created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /document-management/documents/search:
    post:
      tags:
        - Document Management
      operationId: searchDocuments
      parameters:
        - name: page
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            type: integer
            minimum: 1
            default: 20
        - name: sort
          in: query
          description: >-
            Sorting criteria in the format: property,(asc|desc). Multiple criteria supported.
          required: false
          schema:
            type: array
            items:
              type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentSearchFilters'
      responses:
        '200':
          description: Documents found successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDocumentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /document-management/documents/{documentId}/download:
    get:
      tags:
        - Document Management
      operationId: downloadDocument
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDownloadUrlResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        '*/*':
          schema:
            type: object
    Unauthorized:
      description: Unauthorized
      content:
        '*/*':
          schema:
            type: object
    Forbidden:
      description: Forbidden
      content:
        '*/*':
          schema:
            type: object
    NotFound:
      description: Not Found
      content:
        '*/*':
          schema:
            type: object
    Conflict:
      description: Conflict
      content:
        '*/*':
          schema:
            type: object
    InternalServerError:
      description: Internal Server Error
      content:
        '*/*':
          schema:
            type: object
  schemas:
    PresignedUrlRequest:
      type: object
      required:
        - user
        - fileName
        - tags
      properties:
        user:
          type: string
        fileName:
          type: string
        tags:
          type: array
          items:
            type: string
    UploadUrlResponse:
      type: object
      properties:
        url:
          type: string
    ConfirmUploadRequest:
      type: object
      required:
        - user
        - fileName
        - tags
        - objectKey
        - fileSize
        - contentType
      properties:
        user:
          type: string
        fileName:
          type: string
        tags:
          type: array
          items:
            type: string
        objectKey:
          type: string
        fileSize:
          type: integer
          format: int64
        contentType:
          type: string
    DocumentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        size:
          type: integer
          format: int64
        type:
          type: string
        createdAt:
          type: string
          format: date-time
    DocumentSearchFilters:
      type: object
      properties:
        user:
          type: string
          nullable: true
        fileName:
          type: string
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true
    PaginatedDocumentResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/PaginationMetadata'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/DocumentResponse'
    PaginationMetadata:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        itemsPerPage:
          type: integer
          format: int32
        currentItems:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalItems:
          type: integer
          format: int64
    DocumentDownloadUrlResponse:
      type: object
      properties:
        url:
          type: string
